set tabstop=4
set shiftwidth=4
set expandtab
set number

set ignorecase
set smartcase
set incsearch

set mouse=a

execute pathogen#infect()
syntax on
filetype plugin indent on

" FuzzyFinder mapping
map <F3> :FufFile<CR>
" tabnew, tabnew
map \tt :tabnew<CR>
map \tf :tabnew<CR>:FufFile<CR>
map \tn :tabnext<CR>
map \tp :tabprev<CR>

" map Y to copy until the end of line
nnoremap Y y$

" prevent connecting to xserver, in WSL when the clipboard is not disabled - vim will try to connect to the xserver, and if the xserver is not running it will block the starting of vim
" for root - add this line to /etc/vim/vimrc
set clipboard=exclude:.*
